services:
  db:
    image: postgres:latest
    container_name: expense_db
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_PASS}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
volumes:
  db-data:
